### ISSUE TITLE
Fix test errors

### ISSUE THREAD

**Issue by smpallen99** [smpallen99/contact_demo#10]
mix test gives the following errors:

```
  1) test validations validates uniqueness of 'email' field (ContactDemo.UserTest)
     test/models/user_test.exs:125
     ** (MatchError) no match of right hand side value: {:ok, %ContactDemo.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, active: true, confirmation_send_at: nil, confirmation_token: nil, confirmed_at: nil, current_sign_in_at: nil, current_sign_in_ip: nil, email: "lera.stamm@gwendolyn.net", encrypted_password: "$2b$12$9rChK6zFjj9w1QLLM/iIkebn8whpGg4LXG5EzpAHlZPXZBpBhu946", expire_on: #<Date(2016-11-21)>, failed_attempts: 0, id: 65, inserted_at: #Ecto.DateTime<2016-11-21 02:54:48>, last_sign_in_at: nil, last_sign_in_ip: nil, locked_at: nil, name: "Erwin Schimmel", password: "changeme", password_confirmation: "changeme", remember_created_at: nil, reset_password_sent_at: nil, reset_password_token: nil, roles: #Ecto.Association.NotLoaded<association :roles is not loaded>, sign_in_count: 0, unlock_token: nil, updated_at: #Ecto.DateTime<2016-11-21 02:54:48>, username: "amir", users_roles: #Ecto.Association.NotLoaded<association :users_roles is not loaded>}}
     stacktrace:
       test/models/user_test.exs:128: (test)

...

  2) test validations validates uniqueness of 'username' field (ContactDemo.UserTest)
     test/models/user_test.exs:132
     ** (MatchError) no match of right hand side value: {:ok, %ContactDemo.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, active: true, confirmation_send_at: nil, confirmation_token: nil, confirmed_at: nil, current_sign_in_at: nil, current_sign_in_ip: nil, email: "leland.wolf@herta.net", encrypted_password: "$2b$12$FfAT2G.BvcvZfe/j8m.BNuxP6Ei0FiquYotBDhnNx4AaBGrOPVeJy", expire_on: #<Date(2016-11-21)>, failed_attempts: 0, id: 67, inserted_at: #Ecto.DateTime<2016-11-21 02:54:48>, last_sign_in_at: nil, last_sign_in_ip: nil, locked_at: nil, name: "Ross Lemke", password: "changeme", password_confirmation: "changeme", remember_created_at: nil, reset_password_sent_at: nil, reset_password_token: nil, roles: #Ecto.Association.NotLoaded<association :roles is not loaded>, sign_in_count: 0, unlock_token: nil, updated_at: #Ecto.DateTime<2016-11-21 02:54:48>, username: "rowan", users_roles: #Ecto.Association.NotLoaded<association :users_roles is not loaded>}}
     stacktrace:
       test/models/user_test.exs:135: (test)

....................................................

  3) test validations validates uniqueness of 'name' field (ContactDemo.RoleTest)
     test/models/role_test.exs:48
     ** (MatchError) no match of right hand side value: {:ok, %ContactDemo.Role{__meta__: #Ecto.Schema.Metadata<:loaded, "roles">, id: 35, inserted_at: #Ecto.DateTime<2016-11-21 02:54:51>, name: "Otilia Grant", updated_at: #Ecto.DateTime<2016-11-21 02:54:51>, users: #Ecto.Association.NotLoaded<association :users is not loaded>, users_roles: #Ecto.Association.NotLoaded<association :users_roles is not loaded>}}
     stacktrace:
       test/models/role_test.exs:51: (test)

............

  4) test validations validates uniqueness of 'name' field (ContactDemo.GroupTest)
     test/models/group_test.exs:48
     ** (MatchError) no match of right hand side value: {:ok, %ContactDemo.Group{__meta__: #Ecto.Schema.Metadata<:loaded, "groups">, contacts: #Ecto.Association.NotLoaded<association :contacts is not loaded>, contacts_groups: #Ecto.Association.NotLoaded<association :contacts_groups is not loaded>, id: 47, inserted_at: #Ecto.DateTime<2016-11-21 02:54:51>, name: "orchid", updated_at: #Ecto.DateTime<2016-11-21 02:54:51>}}
     stacktrace:
       test/models/group_test.exs:51: (test)

.................................................................

  5) test validations contact_id: if changeset refers to a non-existent contact_id (ContactDemo.ContactGroupTest)
     test/models/contact_group_test.exs:18
     ** (Postgrex.Error) ERROR (undefined_column): column "inserted_at" of relation "contacts_groups" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:463: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:614: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
       test/models/contact_group_test.exs:20: (test)

.

  6) test validations group_id: if changeset refers to a non-existent group_id (ContactDemo.ContactGroupTest)
     test/models/contact_group_test.exs:31
     ** (Postgrex.Error) ERROR (undefined_column): column "inserted_at" of relation "contacts_groups" does not exist
     stacktrace:
       (ecto) lib/ecto/adapters/sql.ex:463: Ecto.Adapters.SQL.struct/6
       (ecto) lib/ecto/repo/schema.ex:397: Ecto.Repo.Schema.apply/4
       (ecto) lib/ecto/repo/schema.ex:193: anonymous fn/11 in Ecto.Repo.Schema.do_insert/4
       (ecto) lib/ecto/repo/schema.ex:614: anonymous fn/3 in Ecto.Repo.Schema.wrap_in_transaction/6
       (ecto) lib/ecto/adapters/sql.ex:508: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
       (db_connection) lib/db_connection.ex:1274: DBConnection.transaction_run/4
       (db_connection) lib/db_connection.ex:1198: DBConnection.run_begin/3
       (db_connection) lib/db_connection.ex:789: DBConnection.transaction/3
       test/models/contact_group_test.exs:33: (test)

...

Finished in 4.7 seconds
171 tests, 6 failures, 24 skipped

Randomized with seed 478064
```

**Comment by vraravam** [comment]
@smpallen99 : could you please retry by completely recreating your test db?

**Comment by smpallen99** [comment]
that fixed the problem. Thanks...

**Comment by vraravam** [comment]
@smpallen99 - for those who come across this project for the first time, I think it might be ok to have the migrations collapsed (I usually collapse migrations - one per table - before going live for v1). It removes some of the initial clutter associated with codebases that are just getting "warmed up". 
Wdyt?
